# Generated by Django 6.0 on 2026-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Статус подтверждения платежа', verbose_name='подтвержден'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Идентификатор платежа в платежной системе Stripe', max_length=255, null=True, verbose_name='ID платежа в Stripe'),
        ),
    ]
