# Generated by Django 6.0 on 2026-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link to video lesson (YouTube only)', max_length=500, null=True, verbose_name='video link'),
        ),
    ]
