# Generated by Django 6.0 on 2026-01-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price in USD', max_digits=10, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Price ID in Stripe system', max_length=255, null=True, verbose_name='Stripe price ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Product ID in Stripe system', max_length=255, null=True, verbose_name='Stripe product ID'),
        ),
    ]
