# Generated by Django 5.2.10 on 2026-02-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_price_course_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is subscription active?', verbose_name='active'),
        ),
    ]
